// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivitiesController from "./activities_controller"
import LeadsController from "./leads_controller"
import ClientsController from "./clients_controller"
import DealsController from "./deals_controller"
import KanbanController from "./kanban_controller"
application.register("activities", ActivitiesController)
application.register("leads", LeadsController)
application.register("clients", ClientsController)
application.register("deals", DealsController)
application.register("kanban", KanbanController)
