// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivitiesController from "./activities_controller"
application.register("activities", ActivitiesController)

import AnalyticsController from "./analytics_controller"
application.register("analytics", AnalyticsController)

import ClientsController from "./clients_controller"
application.register("clients", ClientsController)

import DealsController from "./deals_controller"
application.register("deals", DealsController)

import InvoiceQueuesController from "./invoice_queues_controller"
application.register("invoice-queues", InvoiceQueuesController)

import KanbanController from "./kanban_controller"
application.register("kanban", KanbanController)

import LeadsController from "./leads_controller"
application.register("leads", LeadsController)

import TurboFrameHistoryController from "./turbo_frame_history_controller"
application.register("history", TurboFrameHistoryController)

import FamilyTreeController from "./family_tree_controller"
application.register("family-tree", FamilyTreeController)
